### ISSUE TITLE
MIrrorOp.download recipe URLTestSearcher Issue

### ISSUE THREAD

**Issue by cumcitjamfadmin** [autopkg/moofit-recipes#125]
I've used the MirrorOp recipes (.download and .pkg) for a while and they've worked fine. I tried running the .download recipe earlier today and got the message:

"Error in ...: Processor: URLTextSearcher: Error: No match found on URL: https://www.barco.com/en/support/mirrorop/drivers"

I saw the .download recipe had been updated about two months ago, so I updated it and added the smithjw repo. After doing that and running the new recipe I got another error:

"Error in ....: Processor: URLTextSearcher: Error: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
        
          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        100   241    0   241    0     0    137      0 --:--:--  0:00:01 --:--:--   138

curl: (61) Unrecognized content encoding type. libcurl understands deflate, gzip content encodings."

I don't fully understand how the block for URLTextSearcher works, so I'm not sure the best way to address this.

**Comment by paul-cossey** [comment]
Hi, @cumcitjamfadmin 

I've had a look at this as it's failing for us too. 

The search URL used in `URLTextSearcher` is still valid, but only if you manually put it in a browser. https://www.barco.com/bin/barco/tde/downloadUrl.json?fileNumber=R33050100&tdeType=3

```
{"downloadUrl":"https://barcoprdwebsitefs.azureedge.net/barcoprdfs/Data/secure/downloads/tde/Active/SoftwareFiles/ApplicationSoftware/R33050100_11_ApplicationSw.dmg?s4irCO4t93_ZNTMesJbVk7_YqGi1pRssgnOWCsk0mPDnGICsED8Gv1biQSQem_huptWblSFFnpR4wa0sOmbTYsBbcyaa","isSuccess":true,"isNotFound":false,"isUnauthorized":false}
```

Looks like the vendor has tightened things up to stop scraping 😞

**Comment by MLBZ521** [comment]
This should be fixed in #126.

**Comment by cumcitjamfadmin** [comment]
I ran "autopkg repo-update all" twice to make sure I had the latest version of the recipe, but I'm still getting the same error message:

"Error in ...: Processor: URLTextSearcher: Error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
        
          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        100   241    0   241    0     0    353      0 --:--:-- --:--:-- --:--:--   353
        curl: (61) Unrecognized content encoding type. libcurl understands deflate, gzip content encodings."

**Comment by MLBZ521** [comment]
@cumcitjamfadmin Sorry, I previous message may have mislead you.  This issue should be fixed by #126 when it's merged, which is has not yet been.
